// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use rocket::serde::{ Deserialize, Serialize };

use chrono::NaiveDateTime;
use uuid::Uuid;
use diesel::prelude::*;
#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Insertable, Serialize, Deserialize)]
#[diesel(table_name = event)]
pub struct Event {
    pub id: Uuid,
    pub name: Option<String>,
    pub venue: Option<String>,
    pub address: Option<String>,
    pub contactname: Option<String>,
    pub starts_at: NaiveDateTime,
    pub ends_at: NaiveDateTime,
}

